# Generated by Django 4.2.8 on 2023-12-06 16:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('Point', 'Point'), ('LineString', 'Linestring'), ('Polygon', 'Polygon'), ('MultiPoint', 'Multipoint'), ('MultiLineString', 'Multilinestring'), ('MultiPolygon', 'Multipolygon')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(help_text='地圖幾何資料', srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
